### ISSUE TITLE
广州区调代管上海22扇

### ISSUE THREAD

**Issue by djnken** [XCSWxcsw/Sector-Rudi#8]
如题
当前（2004）：
![image](https://user-images.githubusercontent.com/40542435/79570593-4d8dd780-80ec-11ea-9657-1ed2a168687c.png)
实际情况：
![image](https://user-images.githubusercontent.com/40542435/79570675-7ca44900-80ec-11ea-8005-a365986f702f.png)
图中上海22扇由广州代管

**Comment by XCSWxcsw** [comment]
等俊俊on hold

**Comment by XCSWxcsw** [comment]
可以算是做完了 close #8
